#!/bin/bash

export MODEL_SIZE=50
export BATCH_SIZE=1

export REVERSE_FIRST_K=$1

export MASTER_HOST=127.0.0.1
export MASTER_PORT=1234
export NODE_HOST=127.0.0.1
export NUM_WORKER=2
export NUM_SERVER=2

export INDEX=1
export GPU_IDX=1
export DEBUG_PRINT=1

export NUM_TRAINING_STEP=$2

../code/run_node_resnet.sh \
		$MODEL_SIZE $BATCH_SIZE $REVERSE_FIRST_K $MASTER_HOST $MASTER_PORT $NODE_HOST $NUM_SERVER $NUM_WORKER $INDEX $GPU_IDX $DEBUG_PRINT $NUM_TRAINING_STEP
